# Generated by Django 4.1.2 on 2022-10-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Filter_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('200 T0 500', '200 T0 500'), ('500 T0 1000', '500 T0 1000'), ('1000 T0 2000', '10 T0 2000'), ('2000 T0 3000', '2000 T0 3000'), ('3000 T0 4000', '3000 T0 4000'), ('5000 T0 10000', '5000 T0 10000')], max_length=100)),
            ],
        ),
    ]
