# Generated by Django 4.1.2 on 2022-10-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_color_remove_brand_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=202, unique=True)),
                ('image', models.ImageField(upload_to='Electronic/mega')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('New', 'New'), ('Old', 'Old')], max_length=200)),
                ('stock', models.CharField(choices=[('In Stack', 'In Stack'), ('Out Of Stack', 'Out Of Stack')], max_length=200)),
                ('information', models.TextField(max_length=200)),
                ('dec', models.TextField(max_length=200)),
            ],
        ),
    ]
