# Generated by Django 4.1.2 on 2022-10-24 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_brand_product_category_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
