# Generated by Django 4.1.2 on 2022-10-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_tag_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dec',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='statu',
            field=models.CharField(choices=[('Public', 'Public'), ('Draft', 'Draft')], max_length=250),
        ),
    ]
