# Generated by Django 4.1.2 on 2022-10-28 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateField(default=datetime.date(2022, 10, 28)),
        ),
    ]
