# Generated by Django 4.1.2 on 2022-10-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_order_amount_alter_order_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
