# Generated by Django 4.1.2 on 2022-10-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_order_id_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='Order',
        ),
    ]
