# Generated by Django 4.1.2 on 2022-10-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_order_orderitem_id_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='id_order',
            new_name='order',
        ),
    ]
